# Generated by Django 3.1.6 on 2021-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('fax', models.CharField(max_length=50, null=True)),
                ('focal', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
