# Generated by Django 3.1.6 on 2021-04-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20210402_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rtype', models.CharField(choices=[('Annual Report', 'Annual Report'), ('Quarterly Report', 'Quarterly Report'), ('Minute Report', 'Minute Report'), ('Other Report', 'Other Report')], max_length=200)),
                ('files', models.FileField(upload_to='Report/')),
            ],
        ),
    ]
