# Generated by Django 3.1.6 on 2021-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='provience',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, choices=[('Taplejung', 'Taplejung'), ('Panchthar', 'Panchthar'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Morang', 'Morang'), ('Sunsari', 'Sunsari'), ('Dhankutta', 'Dhankutta'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Bhojpur', 'Bhojpur'), ('Okhaldunga', 'Okhaldunga'), ('Khotang', 'Khotang'), ('Solukhumbu', 'Solukhumbu'), ('Udaypur', 'Udaypur'), ('Saptari', 'Saptari'), ('Siraha', 'Siraha'), ('Dhanusa', 'Dhanusa'), ('Mahottari', 'Mahottari'), ('Sarlahi', 'Sarlahi'), ('Sindhuli', 'Sindhuli'), ('Ramechhap', 'Ramechhap'), ('Dolkha', 'Dolkha'), ('Sindhupalchauk', 'Sindhupalchauk'), ('Kavreplanchauk', 'Kavreplanchauk'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur'), ('Kathmandu', 'Kathmandu'), ('Nuwakot', 'Nuwakot'), ('Rasuwa', 'Rasuwa'), ('Dhading', 'Dhading'), ('Makwanpur', 'Makwanpur'), ('Rauthat', 'Rauthat'), ('Parsa', 'Parsa'), ('Chitwan', 'Chitwan'), ('Gorkha', 'Gorkha'), ('Lamjung', 'Lamjung'), ('Tanahun', 'Tanahun'), ('Syangja', 'Syangja'), ('Kaski', 'Kaski'), ('Manag', 'Manag'), ('Mustang', 'Mustang'), ('Parwat', 'Parwat'), ('Myagdi', 'Myagdi'), ('Baglung', 'Baglung'), ('Gulmi', 'Gulmi'), ('Palpa', 'Palpa'), ('Nawalparasi', 'Nawalparasi'), ('Rupandehi', 'Rupandehi'), ('Arghakhanchi', 'Arghakhanchi'), ('Kapilvastu', 'Kapilvastu'), ('Pyuthan', 'Pyuthan'), ('Rukum', 'Rukum'), ('Rolpa', 'Rolpa'), ('Salyan', 'Salyan'), ('Dang', 'Dang'), ('Bardiya', 'Bardiya'), ('Surkhet', 'Surkhet'), ('Dailekh', 'Dailekh'), ('Banke', 'Banke'), ('Jajarkot', 'Jajarkot'), ('Dolpa', 'Dolpa'), ('Humla', 'Humla'), ('Kalikot', 'Kalikot'), ('Mugu', 'Mugu'), ('Jumla', 'Jumla'), ('Bajura', 'Bajura'), ('Bajhang', 'Bajhang'), ('Achham', 'Achham'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur'), ('Dadeldhura', 'Dadeldhura'), ('Baitadi', 'Baitadi'), ('Darchula', 'Darchula')], max_length=70, null=True),
        ),
    ]
