# Generated by Django 3.1.6 on 2021-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20210708_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dtype', models.CharField(choices=[('KYC Form', 'KYC Form'), ('Proposal Form', 'Proposal Form'), ('Claim Form', 'Claim Form')], max_length=200)),
                ('files', models.FileField(upload_to='Report/')),
            ],
        ),
    ]
