# Generated by Django 3.1.6 on 2021-07-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='slug',
            field=models.SlugField(default='download'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='news'),
        ),
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(default='report'),
        ),
    ]
