# Generated by Django 3.1.6 on 2021-07-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20210713_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscalyear', to='landing.fiscalyear'),
        ),
    ]
