# Generated by Django 3.1.6 on 2021-07-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20210713_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dateof',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
