# Generated by Django 3.1.6 on 2021-07-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_news_dateof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
