# Generated by Django 3.1.6 on 2021-07-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_auto_20210713_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
