# Generated by Django 3.2.6 on 2021-10-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_auto_20210713_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='focal_img',
            field=models.ImageField(default='/static/images/downlogo.PNG', upload_to='focalperson'),
        ),
    ]
