# Generated by Django 3.2.6 on 2021-11-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_alter_branch_focal_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
