# Generated by Django 3.1.6 on 2021-11-28 16:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_alter_branch_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='management/')),
                ('post', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('appointed_date', models.DateField()),
                ('re_appointed_date', models.DateField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('descriptipn', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='management/')),
                ('post', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('appointed_date', models.DateField()),
                ('re_appointed_date', models.DateField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='info@nlgi.com.np', max_length=254)),
                ('number1', models.BigIntegerField(default='01-4442646')),
                ('number2', models.BigIntegerField(blank=True, default='01-4006648', null=True)),
                ('toll_free_no', models.BigIntegerField(blank=True, default='16600199099', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='download',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='report',
            name='slug',
        ),
        migrations.AddField(
            model_name='surveryor',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveryor',
            name='lience_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveryor',
            name='renew_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Sub_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('discontinue', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_product', to='landing.product')),
            ],
        ),
    ]
