# Generated by Django 3.1.6 on 2021-11-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_auto_20211128_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='slug',
            field=models.SlugField(default='download'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='news'),
        ),
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(default='report'),
        ),
    ]
