# Generated by Django 3.1.6 on 2021-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_auto_20211128_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='location',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
