# Generated by Django 3.1.6 on 2021-12-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_setting_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='announcement')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discontinue',
            field=models.BooleanField(default=False),
        ),
    ]
