# Generated by Django 3.1.6 on 2021-12-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_auto_20211202_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
