# Generated by Django 3.1.6 on 2021-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_product_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='bod',
            name='chairman',
            field=models.BooleanField(default=False),
        ),
    ]
