# Generated by Django 3.1.6 on 2021-12-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_bod_chairman'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='departmenthead/')),
                ('post', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
