# Generated by Django 3.1.6 on 2021-12-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0031_auto_20211203_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField()),
            ],
        ),
    ]
