# Generated by Django 3.1.6 on 2021-12-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0032_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_product',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
