# Generated by Django 3.1.6 on 2021-12-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0034_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='number1',
            field=models.CharField(default='01-4442646', max_length=12),
        ),
        migrations.AlterField(
            model_name='setting',
            name='number2',
            field=models.CharField(blank=True, default='01-4006648', max_length=12, null=True),
        ),
    ]
