# Generated by Django 3.1.6 on 2022-01-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0035_auto_20211221_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dateof',
            field=models.DateField(blank=True, null=True),
        ),
    ]
