# Generated by Django 3.1.6 on 2022-01-24 14:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0037_auto_20220124_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bod',
            name='descriptipn',
        ),
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bod',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='BranchName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcement'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bod',
            name='appointed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bod',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='management/'),
        ),
        migrations.AlterField(
            model_name='bod',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bod',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='provience',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departmenthead/'),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='managementteam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='management/'),
        ),
        migrations.AlterField(
            model_name='managementteam',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
