# Generated by Django 3.1.6 on 2022-01-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0038_auto_20220124_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='product_email',
            field=models.EmailField(default='underwriting@nlgi.com.np', max_length=254),
        ),
    ]
