# Generated by Django 3.1.6 on 2022-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0040_ceomessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(upload_to='other/')),
            ],
        ),
    ]
