# Generated by Django 3.1.6 on 2022-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0041_otherdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdownload',
            name='slug',
            field=models.SlugField(default='others'),
        ),
    ]
