# Generated by Django 3.1.6 on 2022-01-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0042_otherdownload_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherdownload',
            old_name='file',
            new_name='files',
        ),
    ]
