# Generated by Django 3.1.6 on 2022-01-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0045_auto_20220128_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsite',
            name='link',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
