# Generated by Django 3.1.6 on 2022-01-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0046_socialsite_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsite',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
