# Generated by Django 3.1.6 on 2022-01-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0047_auto_20220128_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdownload',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='other/'),
        ),
    ]
