# Generated by Django 3.1.6 on 2022-02-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0050_helpcenter_topbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
