# Generated by Django 3.1.6 on 2022-02-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0051_topbar_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='starting_date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
