# Generated by Django 3.1.6 on 2022-02-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0052_auto_20220202_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
