# Generated by Django 3.1.6 on 2022-02-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0054_auto_20220202_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveryor',
            name='lience_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
