# Generated by Django 3.1.6 on 2022-02-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0055_auto_20220208_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
