# Generated by Django 3.1.6 on 2022-02-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0058_ripartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bod',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managementteam',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
