# Generated by Django 3.1.6 on 2022-02-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0059_auto_20220209_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ordering',
        ),
    ]
