# Generated by Django 3.1.6 on 2022-02-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0061_auto_20220209_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bod',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='managementteam',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
