# Generated by Django 3.1.6 on 2022-02-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0063_auto_20220209_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_product',
            name='icons',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
