# Generated by Django 3.1.6 on 2022-02-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0064_sub_product_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_product',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveryor',
            name='ordering',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
